name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Output Run Number
      run: echo ${{ github.run_number }}

    - uses: actions/checkout@v2

    - name: Fetch Git Details for Semantic Versioning
      run: git fetch --prune --unshallow --tags
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/WaybackMachine.Sdk/WaybackMachine.Sdk
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/WaybackMachine.Sdk/WaybackMachine.Sdk
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/WaybackMachine.Sdk.Test
    
    - name: Git Semantic Version
      # You may pin to the exact commit or the version.
      # uses: PaulHatch/semantic-version@bfa36c60873e3ffabedf45184ae74af0df566de6
      uses: PaulHatch/semantic-version@v3.1.1
      with:
        # The branch to count commits on
        branch: "master"
        # The prefix to use to identify tags
        tag_prefix: "v"
        # A string which, if present in a git commit, indicates that a change represents a
        # major (breaking) change
        major_pattern: "(MAJOR)"
        # Same as above except indicating a minor change
        minor_pattern: "(MINOR)"
        # A string to determine the format of the version output
        format: "${major}.${minor}.${patch}-prerelease.${increment}"
        # Optional path to check for changes. If any changes are detected in the path the
        # 'changed' output will true. Enter multiple paths separated by spaces.
        change_path: "src/WaybackMachine.Sdk"
        # Named version, will be used as suffix for name version tag
        namespace: wayback-machine-sdk
