name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Output Run Number
      run: echo ${{ github.run_number }}
      
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/WaybackMachine.Sdk/WaybackMachine.Sdk
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/WaybackMachine.Sdk/WaybackMachine.Sdk
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/WaybackMachine.Sdk.Test
