name: .NET Core
env:
  PROJECT_PATH: src/WaybackMachine.Sdk/WaybackMachine.Sdk
  TEST_PROJECT_PATH: src/WaybackMachine.Sdk.Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: PROJECT_PATH
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: PROJECT_PATH
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: TEST_PROJECT_PATH
