name: mainworkflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Output Run Number
      run: echo ${{ github.run_number }}

    - uses: actions/checkout@v2

    - name: Fetch Git Details for Semantic Versioning
      run: git fetch --prune --unshallow --tags
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/WaybackMachine.DotNet.Client/WaybackMachine.DotNet.Client
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/WaybackMachine.DotNet.Client/WaybackMachine.DotNet.Client
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/WaybackMachine.DotNet.Client.Test
    
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/WaybackMachine.DotNet.Client/WaybackMachine.DotNet.Client/WaybackMachine.DotNet.Client.csproj
        PACKAGE_NAME: WaybackMachineCsharpSdk
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}