name: mainworkflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Output Run Number
      run: echo ${{ github.run_number }}

    - uses: actions/checkout@v2

    - name: Fetch Git Details for Semantic Versioning
      run: git fetch --prune --unshallow --tags
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/WaybackMachine.DotNet.Client
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src/WaybackMachine.DotNet.Client

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/WaybackMachine.DotNet.Client.Test

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner

    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"kristofferandreasen_wayback-machine-dotnet-client" /o:"kristofferandreasen" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
        dotnet build "src/WaybackMachine.DotNet.Client"
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/WaybackMachine.DotNet.Client/WaybackMachine.DotNet.Client.csproj
        PACKAGE_NAME: WaybackMachine.DotNet.Client
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}